#!/usr/bin/env python3
# Token Manager for CST Simulation
# Description: Manages cryptocurrency-like tokens generated by particles.

import sqlite3
import uuid
import json
import logging
import threading
from datetime import datetime

logger = logging.getLogger("TokenManager")

class TokenManager:
    def __init__(self, db_path):
        self.db_path = db_path
        self.conn = sqlite3.connect(db_path, check_same_thread=False)
        self.cur = self.conn.cursor()
        self.token_lock = threading.Lock()  # Added for thread safety
        self.init_db()

    def init_db(self):
        # Create the table if it doesn't exist with the cosmic_value column
        self.cur.execute("""
            CREATE TABLE IF NOT EXISTS tokens (
                token_id TEXT PRIMARY KEY,
                particle_id INTEGER,
                metadata TEXT,
                created_at TEXT,
                cosmic_value REAL DEFAULT 0.0
            )
        """)
        # Check if cosmic_value column exists and add it if not
        self.cur.execute("PRAGMA table_info(tokens)")
        columns = [col[1] for col in self.cur.fetchall()]
        if "cosmic_value" not in columns:
            logger.info("Adding cosmic_value column to existing tokens table")
            with self.token_lock:
                self.cur.execute("ALTER TABLE tokens ADD COLUMN cosmic_value REAL DEFAULT 0.0")
                self.conn.commit()
        else:
            self.conn.commit()
        logger.info(f"TokenManager: Database initialized at '{self.db_path}'.")

    def create_token(self, particle_id, metadata):
        token_id = str(uuid.uuid4())
        created_at = datetime.now().isoformat()
        metadata_json = json.dumps(metadata)
        cosmic_value = float(np.random.uniform(0.1, 1.0))  # Ensure float for SQLite
        with self.token_lock:
            try:
                self.cur.execute(
                    "INSERT INTO tokens (token_id, particle_id, metadata, created_at, cosmic_value) VALUES (?, ?, ?, ?, ?)",
                    (token_id, particle_id, metadata_json, created_at, cosmic_value)
                )
                self.conn.commit()
                logger.info(f"Token {token_id} created for Particle {particle_id} with cosmic_value {cosmic_value}")
                return token_id
            except Exception as e:
                logger.error(f"Token creation failed: {e}")
                return None

    def get_all_tokens(self):
        with self.token_lock:
            self.cur.execute("SELECT token_id, particle_id, metadata, created_at, cosmic_value FROM tokens")
            rows = self.cur.fetchall()
            return [
                {
                    "token_id": r[0],
                    "particle_id": r[1],
                    "metadata": json.loads(r[2]),
                    "created_at": r[3],
                    "cosmic_value": r[4] if r[4] is not None else 0.0
                } for r in rows
            ]

    def get_token_count(self):
        with self.token_lock:
            try:
                self.cur.execute("SELECT COUNT(*) FROM tokens")
                return self.cur.fetchone()[0]
            except Exception as e:
                logger.error(f"Failed to get token count: {e}")
                return 0

    def get_cosmic_value(self):
        with self.token_lock:
            try:
                self.cur.execute("SELECT SUM(cosmic_value) FROM tokens")
                result = self.cur.fetchone()[0]
                return result if result is not None else 0.0
            except Exception as e:
                logger.error(f"Failed to get cosmic value sum: {e}. Returning 0.0")
                return 0.0

    def save_state(self):
        with self.token_lock:
            self.conn.commit()
        logger.info("TokenManager state saved.")

    def shutdown(self):
        with self.token_lock:
            self.conn.close()
        logger.info("TokenManager database closed.")